name: Automated Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# jobs:
#   run-unit-tests:
#     runs-on: ubuntu-latest
#     environment: development
#     defaults:
#       run:
#         working-directory: ./frontend
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*

#       - name: Install Dependencies
#         run: npm ci

#       - name: Run Tests
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
#           NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
#         run: npm test

#       - name: Code Coverage
#         run: npm run coverage

#       - name: Upload Test Results
#         uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: unit-tests-report
#           path: frontend/coverage/
#           retention-days: 30

#   run-e2e-tests:
#     runs-on: ubuntu-latest
#     environment: development
#     defaults:
#       run:
#         working-directory: ./frontend
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*

#       - name: Install Dependencies
#         run: npm install

#       - name: Install Playwright Browsers
#         run: npx playwright install --with-deps

#       - name: Build Application
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
#           NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
#         run: npm run build

#       - name: Run E2E Tests
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
#           NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
#         run: npx playwright test

#       - name: Upload Test Results
#         uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: playwright-report
#           path: frontend/playwright-report/
#           retention-days: 30
